/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Capture
 #	author : miyako
 #	2013/03/05
 #
 # --------------------------------------------------------------------------------*/



// --- Device
void CAPTURE_DEVICE_Get_default(sLONG_PTR *pResult, PackagePtr pParams);
void CAPTURE_DEVICE_LIST(sLONG_PTR *pResult, PackagePtr pParams);

// --- Preview
void CAPTURE_PREVIEW_SET_RECT(sLONG_PTR *pResult, PackagePtr pParams);
void CAPTURE_PREVIEW_SNAP(sLONG_PTR *pResult, PackagePtr pParams);
void CAPTURE_PREVIEW_CLEAR(sLONG_PTR *pResult, PackagePtr pParams);
void CAPTURE_PREVIEW_Get_window(sLONG_PTR *pResult, PackagePtr pParams);
void CAPTURE_PREVIEW_SET_WINDOW(sLONG_PTR *pResult, PackagePtr pParams);
void CAPTURE_PREVIEW_Get_visible(sLONG_PTR *pResult, PackagePtr pParams);
void CAPTURE_PREVIEW_SET_VISIBLE(sLONG_PTR *pResult, PackagePtr pParams);
void CAPTURE_PREVIEW_Create(sLONG_PTR *pResult, PackagePtr pParams);
void CAPTURE_PREVIEW_GET_RECT(sLONG_PTR *pResult, PackagePtr pParams);
