/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.c
 #	source generated by 4D Plugin Wizard
 #	Project : Capture
 #	author : miyako
 #	2013/03/05
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

void PluginMain(int32_t selector, PA_PluginParameters params)
{
	try
	{
		int32_t pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (int32_t pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
// --- Device

		case 1 :
			CAPTURE_DEVICE_Get_default(pResult, pParams);
			break;

		case 2 :
			CAPTURE_DEVICE_LIST(pResult, pParams);
			break;

// --- Preview

		case 3 :
			CAPTURE_PREVIEW_SET_RECT(pResult, pParams);
			break;

		case 4 :
			CAPTURE_PREVIEW_SNAP(pResult, pParams);
			break;

		case 5 :
			CAPTURE_PREVIEW_CLEAR(pResult, pParams);
			break;

		case 6 :
			CAPTURE_PREVIEW_Get_window(pResult, pParams);
			break;

		case 7 :
			CAPTURE_PREVIEW_SET_WINDOW(pResult, pParams);
			break;

		case 8 :
			CAPTURE_PREVIEW_Get_visible(pResult, pParams);
			break;

		case 9 :
			CAPTURE_PREVIEW_SET_VISIBLE(pResult, pParams);
			break;

		case 10 :
			CAPTURE_PREVIEW_Create(pResult, pParams);
			break;

		case 11 :
			CAPTURE_PREVIEW_GET_RECT(pResult, pParams);
			break;

	}
}

// ------------------------------------ Device ------------------------------------


void CAPTURE_DEVICE_Get_default(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_TEXT returnValue;

	// --- write the code of CAPTURE_DEVICE_Get_default here...

	returnValue.setReturn(pResult);
}

void CAPTURE_DEVICE_LIST(sLONG_PTR *pResult, PackagePtr pParams)
{
	ARRAY_TEXT names;


	// --- write the code of CAPTURE_DEVICE_LIST here...

	names.toParamAtIndex(pParams, 1);
}

// ------------------------------------ Preview -----------------------------------


void CAPTURE_PREVIEW_SET_RECT(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT ParamPreview;
	C_LONGINT ParamX;
	C_LONGINT ParamY;
	C_LONGINT ParamW;
	C_LONGINT ParamH;

	ParamPreview.fromParamAtIndex(pParams, 1);
	ParamX.fromParamAtIndex(pParams, 2);
	ParamY.fromParamAtIndex(pParams, 3);
	ParamW.fromParamAtIndex(pParams, 4);
	ParamH.fromParamAtIndex(pParams, 5);

	// --- write the code of CAPTURE_PREVIEW_SET_RECT here...

}

void CAPTURE_PREVIEW_SNAP(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT ParamPreview;
	C_PICTURE ParamSnap;

	ParamPreview.fromParamAtIndex(pParams, 1);

	// --- write the code of CAPTURE_PREVIEW_SNAP here...

	ParamSnap.toParamAtIndex(pParams, 2);
}

void CAPTURE_PREVIEW_CLEAR(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT ParamPreview;

	ParamPreview.fromParamAtIndex(pParams, 1);

	// --- write the code of CAPTURE_PREVIEW_CLEAR here...

}

void CAPTURE_PREVIEW_Get_window(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT ParamPreview;
	C_LONGINT returnValue;

	ParamPreview.fromParamAtIndex(pParams, 1);

	// --- write the code of CAPTURE_PREVIEW_Get_window here...

	returnValue.setReturn(pResult);
}

void CAPTURE_PREVIEW_SET_WINDOW(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT ParamPreview;
	C_LONGINT ParamWindow;

	ParamPreview.fromParamAtIndex(pParams, 1);
	ParamWindow.fromParamAtIndex(pParams, 2);

	// --- write the code of CAPTURE_PREVIEW_SET_WINDOW here...

}

void CAPTURE_PREVIEW_Get_visible(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT ParamPreview;
	C_LONGINT returnValue;

	ParamPreview.fromParamAtIndex(pParams, 1);

	// --- write the code of CAPTURE_PREVIEW_Get_visible here...

	returnValue.setReturn(pResult);
}

void CAPTURE_PREVIEW_SET_VISIBLE(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT ParamPreview;
	C_LONGINT ParamVisible;

	ParamPreview.fromParamAtIndex(pParams, 1);
	ParamVisible.fromParamAtIndex(pParams, 2);

	// --- write the code of CAPTURE_PREVIEW_SET_VISIBLE here...

}

void CAPTURE_PREVIEW_Create(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_TEXT paramDevice;
	C_LONGINT returnValue;

	paramDevice.fromParamAtIndex(pParams, 1);

	// --- write the code of CAPTURE_PREVIEW_Create here...

	returnValue.setReturn(pResult);
}

void CAPTURE_PREVIEW_GET_RECT(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_LONGINT paramPreview;
	C_LONGINT paramX;
	C_LONGINT paramY;
	C_LONGINT paramW;
	C_LONGINT paramH;

	paramPreview.fromParamAtIndex(pParams, 1);

	// --- write the code of CAPTURE_PREVIEW_GET_RECT here...

	paramX.toParamAtIndex(pParams, 2);
	paramY.toParamAtIndex(pParams, 3);
	paramW.toParamAtIndex(pParams, 4);
	paramH.toParamAtIndex(pParams, 5);
}

