/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Capture.h
 #	source generated by 4D Plugin Wizard
 #	Project : Capture
 #	author : miyako
 #	2019/07/31
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_CAPTURE_H
#define PLUGIN_CAPTURE_H

#include "4DPluginAPI.h"

#if VERSIONWIN
#include "windows.h"
#include "dshow.h"
#include "qedit.h"
#include "Shlwapi.h" //PathRemoveFileSpec
#pragma comment(lib, "strmiids")
#pragma comment(lib, "shlwapi")
#endif

#include "ARRAY_TEXT.h"
#include "C_TEXT.h"

#include <map>
#include <mutex>

#pragma mark -

void CAPTURE_DEVICE_Get_default(PA_PluginParameters params);
void CAPTURE_DEVICE_LIST(PA_PluginParameters params);
void CAPTURE_PREVIEW_SET_RECT(PA_PluginParameters params);
void CAPTURE_PREVIEW_SNAP(PA_PluginParameters params);
void CAPTURE_PREVIEW_CLEAR(PA_PluginParameters params);
void CAPTURE_PREVIEW_Get_window(PA_PluginParameters params);
void CAPTURE_PREVIEW_SET_WINDOW(PA_PluginParameters params);
void CAPTURE_PREVIEW_Get_visible(PA_PluginParameters params);
void CAPTURE_PREVIEW_SET_VISIBLE(PA_PluginParameters params);
void CAPTURE_PREVIEW_Create(PA_PluginParameters params);
void CAPTURE_PREVIEW_GET_RECT(PA_PluginParameters params);

#endif /* PLUGIN_CAPTURE_H */
